const menu = [
  {cat:'Rosse',name:'Pizza pane',price:3,desc:'Sale, olio e origano.'},{cat:'Rosse',name:'Marinara',price:4,desc:'Pomodoro, olio, origano e aglio.'},{cat:'Rosse',name:'Margherita',price:5,desc:'Pomodoro e mozzarella.',tag:'CLASSICA'},{cat:'Rosse',name:'Cotto',price:6,desc:'Pomodoro, mozzarella e prosciutto cotto.'},{cat:'Rosse',name:'Würstel',price:6,desc:'Pomodoro, mozzarella e würstel.'},{cat:'Rosse',name:'Diavola',price:6.5,desc:'Pomodoro, mozzarella, spianata piccante o dolce.'},{cat:'Rosse',name:'Cotto e funghi',price:7,desc:'Pomodoro, mozzarella, cotto e funghi champignon.'},{cat:'Rosse',name:'Nettuno',price:8,desc:'Pomodoro, mozzarella, spianata e melanzane grigliate.'},{cat:'Rosse',name:'Napoli',price:7,desc:'Pomodoro, mozzarella, acciughe e capperi.'},{cat:'Rosse',name:'Tonno e cipolla',price:8,desc:'Pomodoro, mozzarella, tonno e cipolla di Tropea.'},{cat:'Rosse',name:'Bufala',price:7.5,desc:'Pomodoro e mozzarella di bufala.'},{cat:'Rosse',name:'Quattro stagioni',price:8.5,desc:'Pomodoro, mozzarella, cotto, funghi, carciofi e olive.'},{cat:'Rosse',name:'Tirolese',price:8,desc:'Pomodoro, mozzarella, provola affumicata e speck.'},{cat:'Rosse',name:'Mr. Bacon',price:8,desc:'Pomodoro, mozzarella, provola affumicata e pancetta tesa.'},{cat:'Rosse',name:'Capricciosa',price:8,desc:'Pomodoro, mozzarella, salame, carciofi, acciughe e olive.'},{cat:'Rosse',name:'Salsiccia e grana',price:7.5,desc:'Pomodoro, mozzarella, salsiccia fresca e grana.'},{cat:'Rosse',name:'Stracciatella e speck',price:8,desc:'Pomodoro, mozzarella, stracciatella e speck.'},{cat:'Rosse',name:'Spianata e carciofi',price:7.5,desc:'Pomodoro, mozzarella, spianata e carciofi.'},{cat:'Rosse',name:'Gustosa',price:8,desc:'Pomodoro, mozzarella, pancetta, mais, funghi e olive.'},{cat:'Rosse',name:'Amatriciana',price:8,desc:'Pomodoro, mozzarella, pancetta, pecorino romano e pepe nero.'},{cat:'Rosse',name:'Parmigiana',price:8.5,desc:'Pomodoro, mozzarella, cotto, melanzane fritte e grana.'},{cat:'Rosse',name:'Mediterranea',price:8.5,desc:'Pomodoro, mozzarella, salsiccia fresca, melanzane grigliate e grana.'},{cat:'Rosse',name:'Delicata',price:9,desc:'Pomodoro, bufala in uscita e prosciutto crudo.'},{cat:'Rosse',name:'Boscaiola',price:8.5,desc:'Pomodoro, mozzarella, salsiccia fresca e funghi porcini*.'},{cat:'Rosse',name:'Porcini e gamberi',price:9.5,desc:'Pomodoro, mozzarella, gamberi* e funghi porcini*.'},{cat:'Rosse',name:'Bombona',price:10,desc:'Pomodoro, mozzarella, salsiccia fresca, würstel, cotto e salame.'},{cat:'Rosse',name:'Moulin Blanc',price:10,desc:'Pomodoro, mozzarella, cotto, funghi, salame, carciofi, olive e grana.',tag:'LA NOSTRA'},{cat:'Rosse',name:'Del Presidente',price:12,desc:'Pomodoro, mozzarella, salsiccia fresca, porcini*, melanzane, crudo, rucola e grana.'},{cat:'Rosse',name:'Frutti di mare',price:15,desc:'Pomodoro, aglio, origano e tutto mare.'},
  {cat:'Bianche',name:'Verdure',price:8,desc:'Mozzarella, pomodorini, melanzane e zucchine grigliate.'},{cat:'Bianche',name:'Bufalina',price:8,desc:'Mozzarella di bufala e pomodorini.'},{cat:'Bianche',name:'Ortolana',price:8,desc:'Mozzarella, zucchine, mais e radicchio.'},{cat:'Bianche',name:'Duchessa',price:8.5,desc:'Mozzarella, panna, crudo e grana.'},{cat:'Bianche',name:'Quattro formaggi',price:8.5,desc:'Mozzarella, provola affumicata, emmenthal e gorgonzola.'},{cat:'Bianche',name:'Norvegese',price:10,desc:'Mozzarella, panna, salmone e rucola.'},{cat:'Bianche',name:'Rape e salsiccia',price:9,desc:'Mozzarella, salsiccia fresca e rape*.'},{cat:'Bianche',name:'Crudaiola',price:9,desc:'Mozzarella, pomodorini, crudo, rucola e grana.'},{cat:'Bianche',name:'Francese',price:12,desc:'Mozzarella, salmone, carciofi e grana.'},{cat:'Bianche',name:'Principessa',price:9,desc:'Mozzarella, panna, gamberi*, zucchine e mais.'},{cat:'Bianche',name:'Valtellina',price:10,desc:'Mozzarella, porcini*, bresaola e grana.'},{cat:'Bianche',name:'Bresaola',price:10,desc:'Mozzarella, pomodorini, bresaola, rucola e grana.'},
  {cat:'Speciali',name:'Bologna',price:9,desc:'Mozzarella, mortadella, granella di pistacchio e stracciatella.'},{cat:'Speciali',name:'Pesto',price:8.5,desc:'Mozzarella, pesto di basilico, pomodori secchi e grana.'},{cat:'Speciali',name:'Noci',price:9,desc:'Mozzarella, gorgonzola, speck e noci.'},{cat:'Speciali',name:'Contessa',price:9,desc:'Mozzarella, datterini gialli, porcini* e pancetta tesa.'},{cat:'Speciali',name:'Deliziosa',price:9.5,desc:'Mozzarella, provola affumicata, cipolla di Tropea, melanzane fritte e nduja.'},{cat:'Speciali',name:'Inferno',price:9,desc:'Pomodoro, mozzarella, gorgonzola, spianata piccante e cipolla di Tropea.'},{cat:'Speciali',name:'Fiori di zucca',price:10,desc:'Mozzarella, provola, acciughe e fiori di zucca*.'},{cat:'Speciali',name:'Trevigiana',price:9,desc:'Mozzarella, radicchio, gorgonzola e speck.'},{cat:'Speciali',name:'Pazza',price:9,desc:'Pomodoro, mozzarella, gorgonzola, salame e crudo.'},{cat:'Speciali',name:'Paesana',price:12,desc:'Mozzarella, salsiccia fresca e peperoni cruschi.',tag:'DEL TERRITORIO'},{cat:'Speciali',name:'Nobile',price:9,desc:'Mozzarella, datterini gialli e bufala in uscita.'},{cat:'Speciali',name:'Montanara',price:10,desc:'Mozzarella, provola affumicata, salsiccia fresca e porcini*.'},{cat:'Speciali',name:'Saporita',price:9,desc:'Pomodoro, bufala, salame, pomodori secchi e grana.'},{cat:'Speciali',name:'Bufalona',price:10,desc:'Pomodorini, bufala, melanzane fritte e spianata piccante.'},{cat:'Speciali',name:'Contadina',price:9,desc:'Mozzarella, datterini gialli, capocollo e stracciatella.'},
  {cat:'Antipasti',name:'Carpaccio di bresaola',price:9,desc:'Bresaola, rucola e grana.'},{cat:'Antipasti',name:'Peperoni cruschi',price:12,desc:''},{cat:'Antipasti',name:"All'italiana",price:8,desc:'Affettati misti, mozzarella, verdure grigliate e olive.'},{cat:'Antipasti',name:'Caprese',price:8,desc:'Mozzarella, pomodoro, olio evo, sale e origano.'},
  {cat:'Secondi',name:'Costata di vitello',price:15,desc:''},{cat:'Secondi',name:'Costata di maiale',price:10,desc:''},
  {cat:'Contorni',name:'Patatine fritte',price:6,desc:'Porzione media.'},{cat:'Contorni',name:'Patatine fritte',price:9,desc:'Porzione grande.'},
  {cat:'Dessert',name:'Cheesecake ai mirtilli',price:5,desc:'Mousse cheesecake, base digestive, salsa ai mirtilli e mirtilli canditi.'},{cat:'Dessert',name:'Cheesecake caramello salato',price:5,desc:'Mousse cheesecake, base digestive e topping al caramello salato.'},{cat:'Dessert',name:'Tiramisù gluten free',price:5,desc:'Crema al mascarpone, granella di savoiardi al caffè e cacao amaro.',tag:'GLUTEN FREE'},{cat:'Dessert',name:'Smeraldi di Bronte',price:6,desc:'Bavarese al pistacchio e fondente 70%, con cioccolatino croccante.'},{cat:'Dessert',name:'Carezza di mandorle',price:6,desc:'Cioccolato croccante, crema alle mandorle, mousse fondente e amarena.'},{cat:'Dessert',name:'Delizia al limone',price:6,desc:'Pan di Spagna e crema al limone Costa di Amalfi IGP.'},
  {cat:'Bevande',name:'Acqua 500 ml',price:1,desc:'Naturale o frizzante.'},{cat:'Bevande',name:'Acqua 1 L',price:1.5,desc:'Naturale o frizzante.'},{cat:'Bevande',name:'Vino rosso locale 500 ml',price:4,desc:''},{cat:'Bevande',name:'Vino rosso locale 1 L',price:7,desc:''},{cat:'Bevande',name:'Coca-Cola / Fanta 33 cl',price:2.5,desc:'In vetro.'},{cat:'Bevande',name:'Coca-Cola / Fanta 1 L',price:6,desc:'In vetro.'},{cat:'Bevande',name:'Estathé 33 cl',price:2.5,desc:'Limone o pesca.'},{cat:'Bevande',name:'Moretti bionda alla spina',price:2.5,desc:'20 cl · 40 cl € 4,50.'},{cat:'Bevande',name:'Moretti rossa alla spina',price:3,desc:'20 cl · 40 cl € 5,50.'},{cat:'Bevande',name:'Montelvini bianco frizzante',price:5,desc:'500 ml · 1 L € 9,00.'},{cat:'Bevande',name:'Heineken 33 cl',price:2.5,desc:'66 cl € 4,50 · Heineken 0.0 33 cl € 3,00.'},{cat:'Bevande',name:'Ichnusa / Messina / Raffo',price:3,desc:'Bottiglia 33 cl.'},{cat:'Bevande',name:'Golden Ale artigianale',price:5.5,desc:"Ispirazione inglese, corpo dolce e finale delicatamente amaro e fruttato."},{cat:'Bevande',name:'Belgian Ale artigianale',price:5.5,desc:'Delicata e vinosa, con profumi erbacei; ideale anche con il pesce.'}
];
// Allineamento al menu ufficiale corrente (luglio 2026).
const discontinued=['Cotto','Würstel','Frutti di mare','Cheesecake ai mirtilli'];
for(let i=menu.length-1;i>=0;i--)if(discontinued.includes(menu[i].name)||menu[i].cat==='Bevande')menu.splice(i,1);
const currentPrices={'Pizza pane':4,'Nettuno':8.5,'Bufala':8,'Quattro stagioni':9,'Capricciosa':9,'Stracciatella e speck':9,'Gustosa':9,'Amatriciana':9,'Parmigiana':10,'Mediterranea':9,'Delicata':10,'Boscaiola':9,'Porcini e gamberi':10,'Del Presidente':14,'Verdure':9,'Bufalina':9,'Ortolana':9,'Duchessa':9,'Quattro formaggi':9,'Norvegese':14,'Rape e salsiccia':10,'Crudaiola':10,'Francese':14,'Principessa':10,'Valtellina':12,'Bresaola':12,'Bologna':10,'Pesto':9,'Noci':10,'Contessa':10,'Deliziosa':11,'Fiori di zucca':12,'Trevigiana':10,'Pazza':11,'Nobile':10,'Montanara':11,'Saporita':10,'Bufalona':12,"All'italiana":10,'Carpaccio di bresaola':12,'Cheesecake caramello salato':6,'Tiramisù gluten free':6,'Smeraldi di Bronte':7,'Carezza di mandorle':7,'Delizia al limone':7};
menu.forEach(x=>{if(currentPrices[x.name]!=null)x.price=currentPrices[x.name]});
menu.push(
  {cat:'Antipasti',name:'Crudo e melone',price:8,desc:'Prosciutto crudo e melone giallo.'},
  {cat:'Contorni',name:'Insalata mista',price:3,desc:''},
  {cat:'Contorni',name:'Insalatona',price:10,desc:'Insalata mista, pomodorini, mozzarella, tonno, mais e olive.'},
  {cat:'Dessert',name:'Cheesecake frutti di bosco',price:7,desc:'Biscotto alle mandorle, crema al formaggio, glassa alle fragole e lamponi e frutti di bosco.'},
  {cat:'Dessert',name:'Frutta realistica · Caffè',price:8,desc:''},{cat:'Dessert',name:'Frutta realistica · Arachide',price:8,desc:''},{cat:'Dessert',name:'Frutta realistica · Pistacchio',price:8,desc:''},
  {cat:'Bevande',name:'Acqua 500 ml',price:1,desc:'Naturale o frizzante.'},{cat:'Bevande',name:'Acqua 1 L',price:1.5,desc:'Naturale o frizzante.'},{cat:'Bevande',name:'Vino rosso locale 500 ml',price:4,desc:''},{cat:'Bevande',name:'Vino rosso locale 1 L',price:7,desc:''},{cat:'Bevande',name:'Coca-Cola 33 cl',price:2.5,desc:'Bottiglia in vetro.'},{cat:'Bevande',name:'Coca-Cola 1 L',price:6,desc:'Bottiglia in vetro.'},{cat:'Bevande',name:'Fanta 33 cl',price:2.5,desc:'Bottiglia in vetro.'},{cat:'Bevande',name:'Fanta 1 L',price:6,desc:'Bottiglia in vetro.'},{cat:'Bevande',name:'Estathé limone 33 cl',price:2.5,desc:''},{cat:'Bevande',name:'Estathé pesca 33 cl',price:2.5,desc:''},{cat:'Bevande',name:'Moretti bionda 20 cl',price:2.5,desc:'Alla spina.'},{cat:'Bevande',name:'Moretti bionda 40 cl',price:4.5,desc:'Alla spina.'},{cat:'Bevande',name:'Moretti rossa 20 cl',price:3,desc:'Alla spina.'},{cat:'Bevande',name:'Moretti rossa 40 cl',price:5.5,desc:'Alla spina.'},{cat:'Bevande',name:'Montelvini bianco frizzante 500 ml',price:5,desc:''},{cat:'Bevande',name:'Montelvini bianco frizzante 1 L',price:9,desc:''},{cat:'Bevande',name:'Heineken 33 cl',price:2.5,desc:''},{cat:'Bevande',name:'Heineken 66 cl',price:4.5,desc:''},{cat:'Bevande',name:'Heineken 0.0 33 cl',price:3,desc:'Analcolica.'},{cat:'Bevande',name:'Ichnusa non filtrata 33 cl',price:3,desc:''},{cat:'Bevande',name:'Messina Cristalli di Sale 33 cl',price:3,desc:''},{cat:'Bevande',name:'Raffo Grezza 33 cl',price:3,desc:''}
);
const photos={'Cheesecake caramello salato':'assets/caramello-salato.jpg','Tiramisù gluten free':'assets/tiramisu-gluten-free.jpg','Cheesecake frutti di bosco':'assets/cheesecake-frutti-bosco.jpg','Smeraldi di Bronte':'assets/smeraldi.jpg','Carezza di mandorle':'assets/carezza-mandorle.jpg','Delizia al limone':'assets/delizia-limone.jpg','Frutta realistica · Caffè':'assets/frutta-realistica-migliorata.png','Frutta realistica · Arachide':'assets/frutta-realistica-migliorata.png','Frutta realistica · Pistacchio':'assets/frutta-realistica-migliorata.png'};
const cats=['Tutto','Rosse','Bianche','Speciali','Antipasti','Secondi','Contorni','Dessert','Bevande'];
let active='Tutto';
const grid=document.querySelector('#menu-grid'), tabs=document.querySelector('#categories'), search=document.querySelector('#search');
const euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n);
function renderPrint(){
  const compactPrint={
    Speciali:[
      {name:'Bologna',price:10,desc:'Mortadella, pistacchio, stracciatella.'},
      {name:'Pesto',price:9,desc:'Pesto, pomodori secchi, grana.'},
      {name:'Noci',price:10,desc:'Gorgonzola, speck, noci.'},
      {name:'Contessa',price:10,desc:'Datterini gialli, porcini, pancetta.'},
      {name:'Deliziosa',price:11,desc:'Provola, Tropea, melanzane, nduja.'},
      {name:'Inferno',price:9,desc:'Gorgonzola, piccante, Tropea.'},
      {name:'Fiori di zucca',price:12,desc:'Provola, acciughe, fiori di zucca.'},
      {name:'Trevigiana',price:10,desc:'Radicchio, gorgonzola, speck.'},
      {name:'Pazza',price:11,desc:'Gorgonzola, salame, crudo.'},
      {name:'Paesana',price:12,desc:'Salsiccia fresca, peperoni cruschi.'},
      {name:'Nobile',price:10,desc:'Datterini gialli, bufala.'},
      {name:'Montanara',price:11,desc:'Provola, salsiccia, porcini.'},
      {name:'Saporita',price:10,desc:'Bufala, salame, pomodori secchi.'},
      {name:'Bufalona',price:12,desc:'Bufala, melanzane, piccante.'},
      {name:'Contadina',price:9,desc:'Datterini, capocollo, stracciatella.'}
    ],
    Antipasti:[
      {name:'Carpaccio di bresaola',price:12,desc:''},
      {name:'Peperoni cruschi',price:12,desc:''},
      {name:"All'italiana",price:10,desc:'Affettati, mozzarella, verdure, olive.'},
      {name:'Caprese',price:8,desc:''},
      {name:'Crudo e melone',price:8,desc:''}
    ],
    Contorni:[
      {name:'Patatine fritte media / grande',price:'€6 / €9',desc:''},
      {name:'Insalata mista',price:3,desc:''},
      {name:'Insalatona',price:10,desc:'Mista, mozzarella, tonno, mais, olive.'}
    ],
    Dessert:[
      {name:'Cheesecake caramello salato',price:6,desc:''},
      {name:'Tiramisù gluten free',price:6,desc:''},
      {name:'Smeraldi di Bronte',price:7,desc:''},
      {name:'Carezza di mandorle',price:7,desc:''},
      {name:'Delizia al limone',price:7,desc:''},
      {name:'Cheesecake frutti di bosco',price:7,desc:''},
      {name:'Frutta realistica · Caffè',price:8,desc:''},
      {name:'Frutta realistica · Arachide',price:8,desc:''},
      {name:'Frutta realistica · Pistacchio',price:8,desc:''}
    ],
    Bevande:[
      {name:'Acqua 500 ml / 1 L',price:'€1 / €1,50',desc:''},
      {name:'Vino rosso locale 500 ml / 1 L',price:'€4 / €7',desc:''},
      {name:'Coca-Cola 33 cl / 1 L',price:'€2,50 / €6',desc:''},
      {name:'Fanta 33 cl / 1 L',price:'€2,50 / €6',desc:''},
      {name:'Estathé limone / pesca 33 cl',price:'€2,50',desc:''},
      {name:'Moretti bionda 20 cl / 40 cl',price:'€2,50 / €4,50',desc:''},
      {name:'Moretti rossa 20 cl / 40 cl',price:'€3 / €5,50',desc:''},
      {name:'Montelvini bianco 500 ml / 1 L',price:'€5 / €9',desc:''},
      {name:'Heineken 33 / 66 / 0.0',price:'€2,50 / €4,50 / €3',desc:''},
      {name:'Ichnusa / Messina / Raffo 33 cl',price:'€3',desc:''}
    ]
  };
  const itemsFor=cat=>compactPrint[cat]||menu.filter(x=>x.cat===cat);
  const price=x=>typeof x.price==='number'?euro(x.price):x.price;
  const block=cat=>`<section class="print-category"><h2>${cat}</h2>${itemsFor(cat).map(x=>`<article class="print-row"><h3>${x.name}</h3><strong>${price(x)}</strong>${x.desc?`<p>${x.desc}</p>`:''}</article>`).join('')}</section>`;
  const page=(side,cats,label)=>`<section class="print-page ${side}"><header class="print-page-head"><div class="print-page-brand"><img src="assets/logo-mark.svg" alt=""><div><h1>MOULIN BLANC</h1><p>PIZZERIA · NOVA SIRI</p></div></div><div class="print-side"><b>${label}</b><span>Viale Siris, 27 · +39 328 916 9724</span></div></header><div class="print-page-columns">${cats.map(block).join('')}</div><footer class="print-page-foot"><span>Comunicare allergie o intolleranze. Disponibile mozzarella senza lattosio. * Prodotto surgelato o di stagione.</span><strong>Coperto € 2,00</strong></footer></section>`;
  document.querySelector('#print-columns').innerHTML=page('front',['Rosse','Bianche'],'LE PIZZE · FRONTE')+page('back',['Speciali','Antipasti','Secondi','Contorni','Dessert','Bevande'],'SPECIALI · CUCINA · RETRO')
}
function renderTabs(){tabs.innerHTML=cats.map(c=>`<button class="category ${c===active?'active':''}" role="tab" aria-selected="${c===active}" data-cat="${c}">${menuL10n.category(c)}</button>`).join('')}
function render(){const q=search.value.trim().toLocaleLowerCase();const list=menu.filter(x=>{const tx=menuL10n.item(x);return(active==='Tutto'||x.cat===active)&&(!q||`${x.name} ${x.desc} ${x.cat} ${tx.name} ${tx.desc}`.toLocaleLowerCase().includes(q))});const card=(x,i=0)=>{const photo=photos[x.name],tx=menuL10n.item(x);return `<article class="menu-item ${photo?'has-photo':''} reveal" style="animation-delay:${Math.min(i,8)*25}ms">${photo?`<img class="item-photo" src="${photo}" alt="${tx.name}" loading="lazy">`:''}<div class="item-name">${tx.name}${x.tag?`<span class="item-tag">${x.tag}</span>`:''}</div><div class="item-price">${euro(x.price)}</div>${tx.desc?`<p class="item-desc">${tx.desc}</p>`:''}</article>`};document.querySelector('#section-title').textContent=q?menuL10n.ui('results'):active==='Tutto'?menuL10n.ui('menu'):menuL10n.category(active);document.querySelector('#section-kicker').textContent=q?'SEARCH':active==='Tutto'?menuL10n.ui('all'):menuL10n.ui('selection');document.querySelector('#item-count').textContent=`${list.length} ${list.length===1?menuL10n.ui('one'):menuL10n.ui('many')}`;if(active==='Tutto'&&!q){const order=['Rosse','Bianche','Speciali','Antipasti','Secondi','Contorni','Dessert','Bevande'];grid.innerHTML=order.map(cat=>{const items=list.filter(x=>x.cat===cat);return `<section class="menu-group"><header class="menu-group-head"><h4>${menuL10n.category(cat)}</h4><span>${items.length} ${menuL10n.ui('many').toUpperCase()}</span></header><div class="menu-group-grid">${items.map(card).join('')}</div></section>`}).join('')}else{grid.innerHTML=list.map(card).join('')}document.querySelector('#empty-state').hidden=!!list.length}
tabs.addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;active=b.dataset.cat;search.value='';renderTabs();render()});search.addEventListener('input',render);document.querySelector('#clear-search').addEventListener('click',()=>{search.value='';search.focus();render()});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();search.focus()}});renderTabs();render();renderPrint();
